#!/usr/bin/env snakemake

import os
import sys
import shutil
import pandas

from metasample import parse_samples, parse_bins, get_sample_id, get_bin_id

shell.executable("bash")

configfile: "metaconfig.yaml"

_samples = parse_samples(config["results"]["raw"]["samples"])

include: "rules/step.smk"
include: "rules/simulation.smk"
include: "rules/fastqc.smk"
include: "rules/trimming.smk"
include: "rules/rmhost.smk"
include: "rules/assembly.smk"
include: "rules/alignment.smk"
include: "rules/binning.smk"
include: "rules/checkm.smk"
include: "rules/annotation.smk"
include: "rules/profilling.smk"


'''
include: "rules/dereplication.smk"
include: "rules/classification.smk"
'''

rule all:
    input:
        profilling_target
