#!/usr/bin/env snakemake
from metasample import parse_samples, parse_bins, get_sample_id, get_bin_id
from metareport import flagstats_summary

shell.executable("bash")

configfile: "metaconfig.yaml"

_samples = parse_samples(config["params"]["samples"])

include: "rules/step.smk"

if config["params"]["begin"] == "raw":
    include: "rules/simulation.smk"
    include: "rules/fastqc.smk"
    include: "rules/trimming.smk"
    include: "rules/rmhost.smk"

include: "rules/assembly.smk"
include: "rules/coassembly.smk"
include: "rules/metaquast.smk"
include: "rules/alignment.smk"
include: "rules/binning.smk"
include: "rules/checkm.smk"
include: "rules/annotation.smk"
include: "rules/profilling.smk"
include: "rules/burst.smk"


'''
include: "rules/dereplication.smk"
include: "rules/classification.smk"
'''

rule all:
    input:
        burst_target
