#!/usr/bin/env snakemake
import os
import sys
import shutil
import pandas as pd

shell.executable("bash")

configfile: "config.yaml"
samples = pd.read_table(config["samples"], index_col=["sample"])
units = pd.read_table(config["units"], index_col=["sample", "unit"], dtype=str)
units.index = units.index.set_levels(
    [i.astype(str) for i in units.index.levels])

rule all:
    input:
        expand("{checkm}/checkm_out/{units.sample}_{units.unit}.checkm.txt",
               checkm=config["results"]["checkm"],
               units=units.reset_index().itertuples())

include: "rules/simulate.smk"
include: "rules/trim.smk"
include: "rules/assembly.smk"
include: "rules/alignment.smk"
include: "rules/binning.smk"
include: "rules/checkm.smk"
